version: '3.4'

services:
  productsservice:
    image: ${DOCKER_REGISTRY-}productsservice
    build:
      context: .
      dockerfile: ProductsService/Dockerfile

  dockercomposeapi:
    image: ${DOCKER_REGISTRY-}dockercomposeapi
    build:
      context: .
      dockerfile: DockerComposeAPI/Dockerfile

  ordersservice:
    image: madhuraju/ordersservice

  db:
    image: postgres
    #build:
    #  context: .
    #  dockerfile: DockerComposeAPI/Dockerfile
